substitutions:
  # -----------------------
  # ADJUST DEVICE NAME HERE
  # -----------------------
  device_name: "homedicator"
  device_friendly_name: "HomeDicator"

  # --------------------------
  # ENTER API AND OTA KEY HERE
  # --------------------------
  api_key: !secret api_encryption_key
  ota_key: !secret ota_password

  # ------------------------------
  # ADJUST YOUR WLAN SETTINGS HERE
  # ------------------------------
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  # ---------------------------------
  # ADJUST TOTAL NUMBER OF PAGES HERE
  # ---------------------------------
  total_pages: "5" # is used to generate navigation dots and their logic (set it to your pages + 1 for the settings page)

  # --------------
  # OTHER SETTINGS
  # --------------
  user_interface_debug_mode: "false" # Draws borders around objects and labels for layouting
  # user_interface_debug_mode: "true" # Draws borders around objects and labels for layouting
     
sensor:
  # ----------------------------------------------------------------------
  # ADD YOUR SENSORS HERE
  # Because of the way ESPHOME works lights, thermostats, etc also go here
  # ----------------------------------------------------------------------
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_import_limit" 
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_export_limit2" 
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_generation_limit" 
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_load_limit" 

  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_csip_aus_import_limit" 
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_csip_aus_export_limit" 
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_csip_aus_generation_limit" 
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_csip_aus_load_limit" 

  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_vpp_import_limit" 
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_vpp_export_limit" 
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_vpp_generation_limit" 
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_vpp_load_limit" 

  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_local_import_limit" 
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_local_export_limit" 
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_local_generation_limit" 
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "energy_local_load_limit" 


  # ----------------------------
  # INTERNAL SENSORS DON'T TOUCH
  # ----------------------------
  - !include HomeDicator/core/config/sensors/wifi_signal.yaml
  - !include HomeDicator/core/config/sensors/wifi_signal_percent.yaml
  

binary_sensor:
  # ---------------------
  # ADD YOUR SENSORS HERE
  # ---------------------


  # ----------------------------
  # INTERNAL SENSORS DON'T TOUCH
  # ----------------------------
  - !include HomeDicator/core/config/binary_sensors/indicator_button.yaml
         
switch:
  # ----------------------
  # ADD YOUR SWITCHES HERE
  # ----------------------


  # -----------------------------
  # INTERNAL SWITCHES DON'T TOUCH
  # -----------------------------
  - !include HomeDicator/core/config/switches/use_24h_clock_switch.yaml


lvgl:  
  pages:
    - id: page_1
      bg_opa: TRANSP
      widgets:
        - !include
            file: HomeDicator/user_interface/templates/page_title.yaml
            vars:
              title: "Dynamic Power Limits"
        - obj:
            styles: content_container
            layout: 
              type: FLEX
              flex_flow: ROW_WRAP
              flex_align_main: LV_FLEX_ALIGN_START
              flex_align_cross: CENTER
            widgets:
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "energy_import_limit"
                    icon: "\U000F192C"
                    unit: "kW"
                    title: "Import Limit"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "energy_export_limit2"
                    icon: "\U000F192D"
                    unit: "kW"
                    title: "Export Limit"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "energy_generation_limit"
                    icon: "\U000F0A72"
                    unit: "kW"
                    title: "Generation Limit"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "energy_load_limit"
                    icon: "\U000F1903"
                    unit: "kW"
                    title: "Load Limit"

    - id: page_2
      bg_opa: TRANSP
      widgets:
        - !include
            file: HomeDicator/user_interface/templates/page_title.yaml
            vars:
              title: "CSIP-Aus Dynamic Limits"
        - obj:
            styles: content_container
            layout: 
              type: FLEX
              flex_flow: ROW_WRAP
              flex_align_main: LV_FLEX_ALIGN_START
              flex_align_cross: CENTER
            widgets:
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/wide_half_height.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "energy_csip_aus_import_limit"
                    icon: "\U000F192C"
                    unit: "kW"
                    title: "Import Limit"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/wide_half_height.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "energy_csip_aus_export_limit"
                    icon: "\U000F192D"
                    unit: "kW"
                    title: "Export Limit"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/wide_half_height.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "energy_csip_aus_generation_limit"
                    icon: "\U000F0A72"
                    unit: "kW"
                    title: "Generation Limit"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/wide_half_height.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "energy_csip_aus_load_limit"
                    icon: "\U000F1903"
                    unit: "kW"
                    title: "Load Limit"

    - id: page_3
      bg_opa: TRANSP
      widgets:
        - !include
            file: HomeDicator/user_interface/templates/page_title.yaml
            vars:
              title: "VPP Dynamic Limits"
        - obj:
            styles: content_container
            layout: 
              type: FLEX
              flex_flow: ROW_WRAP
              flex_align_main: LV_FLEX_ALIGN_START
              flex_align_cross: CENTER
            widgets:
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/wide_half_height.yaml
                  vars:
                    color: 0x41eebf
                    hass_sensor_id: "energy_vpp_import_limit"
                    icon: "\U000F192C"
                    unit: "kW"
                    title: "Import Limit"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/wide_half_height.yaml
                  vars:
                    color: 0x41eebf
                    hass_sensor_id: "energy_vpp_export_limit"
                    icon: "\U000F192D"
                    unit: "kW"
                    title: "Export Limit"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/wide_half_height.yaml
                  vars:
                    color: 0x41eebf
                    hass_sensor_id: "energy_vpp_generation_limit"
                    icon: "\U000F0A72"
                    unit: "kW"
                    title: "Generation Limit"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/wide_half_height.yaml
                  vars:
                    color: 0x41eebf
                    hass_sensor_id: "energy_vpp_load_limit"
                    icon: "\U000F1903"
                    unit: "kW"
                    title: "Load Limit"

    - id: page_4
      bg_opa: TRANSP
      widgets:
        - !include
            file: HomeDicator/user_interface/templates/page_title.yaml
            vars:
              title: "Local Dynamic Limits"
        - obj:
            styles: content_container
            layout: 
              type: FLEX
              flex_flow: ROW_WRAP
              flex_align_main: LV_FLEX_ALIGN_START
              flex_align_cross: CENTER
            widgets:
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/wide_half_height.yaml
                  vars:
                    color: 0xbf41ee
                    hass_sensor_id: "energy_local_import_limit"
                    icon: "\U000F192C"
                    unit: "kW"
                    title: "Import Limit"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/wide_half_height.yaml
                  vars:
                    color: 0xbf41ee
                    hass_sensor_id: "energy_local_export_limit"
                    icon: "\U000F192D"
                    unit: "kW"
                    title: "Export Limit"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/wide_half_height.yaml
                  vars:
                    color: 0xbf41ee
                    hass_sensor_id: "energy_local_generation_limit"
                    icon: "\U000F0A72"
                    unit: "kW"
                    title: "Generation Limit"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/wide_half_height.yaml
                  vars:
                    color: 0xbf41ee
                    hass_sensor_id: "energy_local_load_limit"
                    icon: "\U000F1903"
                    unit: "kW"
                    title: "Load Limit"


   # ---------------------------
   # SETTINGS PAGE - DON'T TOUCH
   # ---------------------------
    - !include HomeDicator/user_interface/pages/settings.yaml


  # ----------------------
  # INTERNAL - DON'T TOUCH
  # ----------------------
  disp_bg_color: 0x1b1b1b
  gradients: !include HomeDicator/core/config/lvgl/gradients.yaml
  on_idle: !include HomeDicator/core/config/lvgl/on_idle.yaml
  top_layer: !include HomeDicator/user_interface/pages/top_layer/top_layer.yaml
  theme: !include HomeDicator/user_interface/theme/theme.yaml
  style_definitions: !include HomeDicator/user_interface/theme/style_definitions.yaml


# ----------------------
# INTERNAL - DON'T TOUCH
# ----------------------
<<: !include HomeDicator/core/config/fonts.yaml
<<: !include HomeDicator/core/config/esphome.yaml
<<: !include HomeDicator/core/config/hardware.yaml
<<: !include HomeDicator/core/config/scripts.yaml
<<: !include HomeDicator/core/config/light.yaml
<<: !include HomeDicator/core/config/time.yaml
<<: !include HomeDicator/core/config/select.yaml
<<: !include HomeDicator/core/config/globals.yaml
