obj:
  height: SIZE_CONTENT
  width: SIZE_CONTENT
  pad_all: 0
  bg_opa: TRANSP
  widgets:
    - obj:
        styles: info_or_button_tile_wide
        width: 440
        height: 78
        pad_left: 25
        pad_right: 11
        layout: 
          type: FLEX
          flex_flow: ROW
          flex_align_main: SPACE_BETWEEN
          flex_align_cross: CENTER
          flex_align_track: CENTER
          pad_row: 0
        widgets:
          - obj:
              bg_opa: COVER
              bg_color: ${color}
              pad_all: 0
              height: 52
              width: 80
              radius: 25
              layout:
                type: FLEX
                flex_flow: COLUMN
                flex_align_main: CENTER
                flex_align_cross: CENTER
                flex_align_track: CENTER
              widgets:
                - label:
                    styles: info_or_button_tile_icon
                    text: ${icon}          
          - obj:
              bg_opa: TRANSP
              width: SIZE_CONTENT
              height: SIZE_CONTENT
              pad_all: 5
              x: 155
              y: 23
              layout: 
                type: FLEX
                flex_flow: ROW
                flex_align_main: CENTER
                flex_align_cross: END
                pad_row: 0
                pad_column: 3
              widgets:
                - label:
                    id: lvgl_value_label_${hass_sensor_id}
                    text_font: libreFranklin24
                    text_color: 0xffffff
                    text: "n/a"
                - label:
                    text_font: libreFranklin20Light
                    text_color: 0xffffff
                    text: "${unit}"
    
